- README.md
- examples/yoti_example_flask/Dockerfile
- examples/yoti_example_flask/app.py
- examples/yoti_example_flask/docker-compose.yml
- examples/yoti_example_flask/requirements.txt
- plugins/flask_yoti/README.md
I'll do the Django project next in the same way
> [SDK-158]: Added docker files for Flask example application

- README.md
- examples/yoti_example_django/requirements.in
- examples/yoti_example_django/requirements.txt
- examples/yoti_example_django/yoti_example/templates/profile.html
- examples/yoti_example_flask/requirements.in
- examples/yoti_example_flask/requirements.txt
- examples/yoti_example_flask/templates/profile.html
- Regenerated example projects' requirements file
- Renamed `User ID` to `RememberMeID` in examples
> SDK-556: Update Example projects

- README.md
- examples/yoti_example_django/requirements.in
- examples/yoti_example_django/requirements.txt
- examples/yoti_example_django/yoti_example/templates/profile.html
- examples/yoti_example_flask/requirements.in
- examples/yoti_example_flask/requirements.txt
- examples/yoti_example_flask/templates/profile.html
Reviewed in single PR - https://github.com/getyoti/yoti-python-sdk/pull/36
> development -> master

- README.md
- examples/yoti_example_django/Dockerfile
- examples/yoti_example_django/requirements.in
- examples/yoti_example_django/requirements.txt
- examples/yoti_example_flask/requirements.in
- examples/yoti_example_flask/requirements.txt
- requirements.in
- requirements.txt
- requirements_tox.txt
- yoti_python_sdk/version.py
- Update packages:
- "requests" in SDK and example projects
- "cryptography" in example projects
> SDK-783: Packages update

- README.md
- examples/yoti_example_flask/requirements.in
- examples/yoti_example_flask/requirements.txt
- yoti_python_sdk/client.py
- yoti_python_sdk/tests/test_client.py
- Point to Travis for supported versions in README
- Update Jinja version - [CVE](https://nvd.nist.gov/vuln/detail/CVE-2016-10745)
- Update X-Yoti-SDK-Version header value
> SDK-777;SDK-908: Versions

- examples/yoti_example_django/requirements.in
- examples/yoti_example_django/requirements.txt
- examples/yoti_example_flask/requirements.in
- examples/yoti_example_flask/requirements.txt
- requirements.in
- requirements.txt
- yoti_python_sdk/version.py
- [CVE-2019-11324](https://nvd.nist.gov/vuln/detail/CVE-2019-11324)
- Also ordered requirements.in alphabetically
- Will be released in 2.7.1
> SDK-922: Add urllib>=1.24.2 requirement

- examples/yoti_example_django/requirements.in
- examples/yoti_example_django/requirements.txt
- yoti_python_sdk/tests/test_profile.py
- CVE - <https://nvd.nist.gov/vuln/detail/CVE-2019-12308> - doesn't seem like it will actually affect the project, but we might as well update anyway
- Manual testing I did - ran the Django example project and completed a share
- Also noticed that a test was showing a warning in the test output, so I fixed that too
> SDK-999: Update Django

- examples/yoti_example_django/requirements.in
- examples/yoti_example_django/requirements.txt
- yoti_python_sdk/tests/test_profile.py
- Just changes in tests & Django project, so no release required
> Merge development -> master

- requirements.in
- requirements.txt
- yoti_python_sdk/activity_details.py
- yoti_python_sdk/tests/test_activity_details.py
ActivityDetails.remember_me_id property
ActivityDetails.user_id attribute changed to property with setter decorator
ActivityDetails.user_id marked as deprecated.
> SDK-570: Add remember_me_id to ActivityDetails

- yoti_python_sdk/version.py
- Bumped the version number to 2.8.2 for release
> Release 2.8.2: Bump version number

- examples/yoti_example_flask/requirements.in
- examples/yoti_example_flask/requirements.txt
- Update requirements.in file for example Flask project to require Flask>=1.0.4
- Update requirements.in file for example Flask project to require Yoti>=2.8.1
> SDK-1161: Update Flask dependency

- examples/aml/requirements.txt
- examples/yoti_example_django/requirements.in
- examples/yoti_example_django/requirements.txt
- examples/yoti_example_flask/requirements.in
- examples/yoti_example_flask/requirements.txt
- Update example projects to use latest released version of Yoti Python SDK
> Release 2.8.2: Update example project versions

- yoti_python_sdk/anchor.py
- yoti_python_sdk/attribute.py
- Update constructors to use None as default value and assign in the constructor itself
> SDK-1135: Change parameters to not initialise objects

- README.md
- Updated the README to include information about the `ApplicationProfile` now available from `ActivityDetails`
> SDK-1164: Update README with Application Profile

- examples/yoti_example_django/yoti_example/templates/attribute_snippet.html
- examples/yoti_example_django/yoti_example/views.py
- examples/yoti_example_flask/app.py
- examples/yoti_example_flask/templates/profile.html
- yoti_python_sdk/activity_details.py
- yoti_python_sdk/age_verification.py
- yoti_python_sdk/exceptions.py
- yoti_python_sdk/profile.py
- yoti_python_sdk/tests/test_age_verification.py
- yoti_python_sdk/tests/test_profile.py
* `AgeVerification` class
* `age` property - the requested age the date of birth should be over/under
* `check_type` property - the type of check performed (age over/under)
* `result` property - the result of the check (True/False)
* `attribute` property - the attribute the age verification was derived from
* `Profile` class
* `verifications` property - a dictionary of all the age verifications
* `get_age_verifications()` - returns a list of all the age verifications
* `find_age_over_verification(age_over)` - returns a matching `AgeVerification` based on `age_over` parameter
* `find_age_under_verification(age_under)` - returns a matching `AgeVerification` based on `age_under` parameter
* `try_parse_age_verified_field` method on `ActivityDetails` class
> SDK-573: Implement AgeVerification

- sonar-project.properties
- yoti_python_sdk/dynamic_sharing_service/extension/location_constraint_extension_builder.py
- yoti_python_sdk/tests/dynamic_sharing_service/extension/test_location_constraint_extension_builder.py
- yoti_python_sdk/version.py
* Corrected method name for longitude in the location constraint extension builder
> Release 2.9.2

- README.md
* Add `structured_postal_address` to README
> SDK-937: Add Structured Postal Address to README

- CONTRIBUTING.md
* Contributing file outlining any information external users must follow if they wish to contribute to the project
> SDK-534: Contributing File

- sonar-project.properties
- yoti_python_sdk/version.py
* Bump version number to `3.0.0`
> NA: Bump version number to 3.0.0

- yoti_python_sdk/date_parser.py
- yoti_python_sdk/dynamic_sharing_service/extension/third_party_attribute_extension.py
- yoti_python_sdk/tests/dynamic_sharing_service/extension/test_third_party_attribute_extension.py
* Add `ThirdPartyAttributeExtension`
> SDK-1260: Add ThirdPartyAttributeExtension

- .coveragerc
- .travis.yml
- requirements.in
- requirements.txt
- setup.py
- sonar-project.properties
- yoti_python_sdk/document_details.py
- yoti_python_sdk/tests/test_document_details.py
- yoti_python_sdk/version.py
* Document Details Attribute to support redacted document numbers, such as an Aadhaar number.
> Release 2.10.1

- .github/ISSUE_TEMPLATE/custom.md
Content at top of new issues: 
```
#
#
#
#
#
```
> SDK-1480: Create custom issue template

- yoti_python_sdk/doc_scan/session/retrieve/id_document_resource_response.py
- yoti_python_sdk/doc_scan/session/retrieve/resource_container.py
- yoti_python_sdk/doc_scan/session/retrieve/task_response.py
- yoti_python_sdk/tests/doc_scan/session/retrieve/test_id_document_resource_response.py
- yoti_python_sdk/tests/doc_scan/session/retrieve/test_resource_container.py
- yoti_python_sdk/tests/doc_scan/session/retrieve/test_task_response.py
* `IdDocumentResourceResponse`
* `@property text_extraction_tasks`
* `ResourceContainer`
* `@property zoom_liveness_resources`
* `TextExtractionTaskResponse`
* `@property generated_text_data_checks`
> SDK-1559: Add missing filter methods for Doc scan

- yoti_python_sdk/doc_scan/session/retrieve/liveness_resource_response.py
- yoti_python_sdk/tests/doc_scan/session/retrieve/test_liveness_resource_response.py
* `LivenessResourceResponse`
* `@property liveness_type`
> SDK-1547: Add liveness_type to LivenessResourceResponse

- requirements.in
- requirements.txt
- setup.py
- Added extra steps to release process to ensure that we check the README can be parsed before uploading to PyPi
> SDK-1600: Use README for project description

- .travis.yml
- README.md
- Add SonarCloud badges, remove Coveralls (coverage provided in SonarCloud)
> SDK-1390: Sonar Cloud 

- examples/doc_scan/templates/index.html
See SDK-1678
Going into master as we want to get this out now, and it doesn't need to be in a release. Will merge into development after.
> SDK-1680: Update iframe html to allow full screen

- README.md
> Merge master → development

- yoti_python_sdk/doc_scan/session/create/sdk_config.py
- yoti_python_sdk/doc_scan/session/create/session_spec.py
- yoti_python_sdk/doc_scan/session/retrieve/id_document_resource_response.py
- yoti_python_sdk/doc_scan/session/retrieve/resource_response.py
As I was going through Go Doc Scan I noticed a few things that I thought should be changed
> SDK-1299: Update Doc Scan docs

- examples/doc_scan/templates/success.html
- yoti_python_sdk/doc_scan/session/create/session_spec.py
- yoti_python_sdk/doc_scan/session/retrieve/get_session_result.py
- yoti_python_sdk/tests/doc_scan/session/create/test_session_spec.py
- yoti_python_sdk/tests/doc_scan/session/retrieve/test_get_session_result.py
- Ability to block the collection of bio-metric consent
> SDK-1739: Biometric Consent

- examples/doc_scan/templates/success.html
- yoti_python_sdk/doc_scan/session/retrieve/page_response.py
- yoti_python_sdk/tests/doc_scan/session/retrieve/test_page_response.py
- Support for document page frames
> SDK-1772: Document Page Frames

- examples/aml/requirements.txt
- examples/doc_scan/requirements.in
- examples/doc_scan/requirements.txt
- examples/yoti_example_django/requirements.in
- examples/yoti_example_django/requirements.txt
- examples/yoti_example_flask/requirements.in
- examples/yoti_example_flask/requirements.txt
- Update demo SDK version to latest release
> NA: Update demo SDK version

- examples/doc_scan/app.py
- examples/doc_scan/templates/privacy.html
- yoti_python_sdk/doc_scan/session/create/sdk_config.py
- yoti_python_sdk/tests/doc_scan/session/create/test_sdk_config.py
- Support for custom privacy policy URL
> SDK-1825: Privacy Policy URL

- .github/dependabot.yml
> adding myself to dependabot

- .gitignore
- yoti_python_sdk/doc_scan/session/create/sdk_config.py
- yoti_python_sdk/tests/doc_scan/session/create/test_sdk_config.py
- yoti_python_sdk/tests/test_anchor.py
Adding boolean flag to sdk config
> [SDK-1998] adding handoff flag

- yoti_python_sdk/doc_scan/session/create/session_spec.py
- yoti_python_sdk/doc_scan/session/retrieve/create_session_result.py
- yoti_python_sdk/tests/doc_scan/session/create/test_session_spec.py
Add support for Session Deadline
> [SDK-1980] Add support for Session Deadline

- yoti_python_sdk/doc_scan/session/create/subcheck/__init__.py
- yoti_python_sdk/doc_scan/session/create/subcheck/issuing_authority_sub_check.py
- yoti_python_sdk/doc_scan/session/create/subcheck/sub_check.py
- yoti_python_sdk/tests/doc_scan/session/create/subcheck/test_issuing_authority_sub_check.py
[SDK-2004] Add support for issuing authority sub check
> [SDK-2004] Add support for issuing authority sub check

- .github/workflows/tests.yaml
- examples/yoti_example_flask/requirements.in
- examples/yoti_example_flask/requirements.txt
- Fix GitHub actions
- Use Python 3.9
- Update Jinja
> NA: Fix GitHub actions
