getyoti/yoti-python-sdk

- config.py
- yoti_python_sdk/client.py
- yoti_python_sdk/tests/test_client.py
Since the identifier is referenced from both the code and the tests, I placed it in a config file, implemented in the same style as the conftest.py which is currently used. Tests pass after this change.
> [SDK-113]: Added X-SDK identifier to headers sent in HTTP requests

- .gitignore
- README.md
- plugins/django_yoti/requirements.txt
- plugins/django_yoti/setup.py
- plugins/flask_yoti/requirements.txt
- plugins/flask_yoti/setup.py
- setup.py
Changed to version 2.0.0, after addition of X-SDK headers and added keywords. Similar to the .NET version, I decided to be consistent with the versioning there - even though we've changed the name of the package and could feasibly start at 1.0.0 as it's a new package, there is a smaller chance of confusion if we use 2.0.0. I'll publish the package once this change is approved.
> [SDK-39]: Changed to version 2.0.0, after addition of X-SDK headers

- MANIFEST.in
- setup.py
Changed tests to be pruned in the manifest file.  Example projects already are not included.
> [SDK-167]: Removed tests from package output

- README.md
- examples/yoti_example_django/yoti_example/templates/profile.html
- examples/yoti_example_django/yoti_example/views.py
- examples/yoti_example_flask/app.py
- examples/yoti_example_flask/templates/profile.html
- yoti_python_sdk/activity_details.py
- yoti_python_sdk/tests/conftest.py
- yoti_python_sdk/tests/test_activity_details.py
- Test coverage for `remember_me_id` (called `user_id` until the major release) were limited to the tests contained in the "successful_receipt" tests, so I added a couple of small unit tests for that which cover the same functionality as `parent_remember_me_id` too
- Line changes in the README were just changing tabs to spaces
> SDK-711: Add ParentRememberMeID

- yoti_python_sdk/tests/test_anchor.py
- Tests run in any timezone (considers DST)
- Works in Python 2.7 and 3.x
> SDK-781: Anchor timestamp tests

- yoti_python_sdk/anchor.py
- yoti_python_sdk/tests/anchor_parser.py
- yoti_python_sdk/tests/test_anchor.py
- yoti_python_sdk/tests/test_attribute.py
- Ensured any anchor can be parsed, and won't affect parsing of other anchors
- renamed a few methods to make it clearer what they're doing (updated utc_offset name as it shadowed utc_offset in outer scope)
> SDK-662: Add try blocks to anchor parsing, tidy up tests

- yoti_python_sdk/anchor.py
- yoti_python_sdk/profile.py
- yoti_python_sdk/protobuf/protobuf.py
- yoti_python_sdk/tests/test_profile.py
- Only CT_STRING attributes should allow an empty value
- ApplicationProfile hasn't been added to Python SDK yet, but once it does, we will need to add the exception for ApplicationLogo
- Added extra propagation check to logging from other PR
> SDK-856: Allow empty for string content types only

- yoti_python_sdk/activity_details.py
- yoti_python_sdk/image.py
- yoti_python_sdk/profile.py
- yoti_python_sdk/protobuf/protobuf.py
- yoti_python_sdk/tests/test_image.py
- yoti_python_sdk/tests/test_protobuf.py
- Creating the new Image object before we add the DocumentImages attribute
- I have left Image.base64_content calling Protobuf().image_uri_based_on_content_type in this PR, as that has moved on my other branch. When I rebase the other branch I will change the location of this (so will leave the TODO in there until then) 
- Since selfie currently is just an attribute with the byte value as the value (retrieved with selfie.value), and base64URL is retrieved from the ActivityDetails, we can't make a non-breaking change to the object that is returned. When we do the major release, I will change the selfie to return this new Image object.
> SDK-594: new Image type

- yoti_python_sdk/profile.py
- Haven't removed `given_names`, just moved it so it was next to `family_name` and `family_name`
> SDK-993: Add docstrings to attribute properties

- yoti_python_sdk/__init__.py
- yoti_python_sdk/client.py
- yoti_python_sdk/tests/test_client.py
- Add environment variable support to allow SSL verification to be turned off
- Add environment variable support to allow overriding of the whole API URL.
> SDK-826: Verify SSL and API Endpoint Environment Variables

- examples/yoti_example_flask/app.py
- Updated Flask example to reference `remember_me_id` rather than `user_id`
- This isn't actually being displayed on the profile, but I thought it's useful to keep in there, so we can show clients how to retrieve it
> SDK-570: Update user_id in Flask example

- sonar-project.properties
- yoti_python_sdk/endpoint.py
- yoti_python_sdk/profile.py
- yoti_python_sdk/tests/test_profile.py
- yoti_python_sdk/version.py
* Incorrect endpoint in get_dynamic_share_request_url when no_params=True
* KeyError in age verifications over/under when no age verifications were requested
> SDK-1197: Fix incorrect endpoint

- yoti_python_sdk/dynamic_sharing_service/extension/location_constraint_extension_builder.py
- yoti_python_sdk/tests/dynamic_sharing_service/extension/test_location_constraint_extension_builder.py
* Fix broken `location_constraint_extention`, misspelling of longitude causes invalid payload to be generated.
> SDK-1196: Correct mispelling of longitude in Python SDK

- yoti_python_sdk/client.py
- yoti_python_sdk/http.py
- yoti_python_sdk/tests/test_http.py
* `X-Auth-Key` removed from `SignedRequest`'s default headers
* `X-Auth-Key` being set by business logic in `Client`
> SDK-1206: Remove X-Auth-Key from default headers of request builder

- .travis.yml
- requirements.in
- requirements.txt
- setup.py
* Support for Python 3.8 to travis file
* Updated `cryptography` to use >= 2.7.0 (from 2.4.0)
* Override `cffi` to use latest 1.x minor version (>= 1.13.0)
> SDK-1254: Update dependencies

- yoti_python_sandbox/tests/test_sandbox_client.py
- yoti_python_sdk/attribute_parser.py
- yoti_python_sdk/tests/test_attribute_parser.py
* Updated all CT_DATE protobufs to be converted into a `datetime.date` object instead of just a string.
> SDK-681: Date object for CT_DATE Proto

- pytest.ini
- yoti_python_sandbox/tests/test_sandbox_client.py
* Pytest configuration changed to run all `test_*.py` files instead of specific directory (allows other modules to be added and not have to be added to the configuration)
* Test in sandbox fixed where old module was being patched
> SDK-1285: Update pytest configuration

- yoti_python_sdk/dynamic_sharing_service/policy/wanted_attribute_builder.py
- yoti_python_sdk/tests/dynamic_sharing_service/policy/test_wanted_attribute_builder.py
* Add assertions to WantedAttributeBuilder.build to check that the attribute name is set and not-empty.
> SDK-1281: Prevent Empty Attribute Names in Wanted Attribute

- .travis.yml
- setup.py
* Python 2.7 is reaching EoL at the end of December 2019 so for the major we are going to drop any future support for Python 2.
* Removed any testing for Python 2 from travis, and updated tags in setup.py
> SDK-1288: Drop testing for Python 2

- yoti_python_sdk/activity_details.py
- yoti_python_sdk/anchor.py
- yoti_python_sdk/tests/test_activity_details.py
- yoti_python_sdk/tests/test_anchor.py
- yoti_python_sdk/tests/test_client.py
* `ActivityDetails.timestamp` and `Anchor.signed_timestamp` are now always returned as a UTC timestamp.
> SDK-891: Ensure UTC Dates are used

- yoti_python_sandbox/anchor.py
- yoti_python_sdk/anchor.py
- yoti_python_sdk/anchor_parser.py
- yoti_python_sdk/config.py
- yoti_python_sdk/profile.py
- yoti_python_sdk/tests/anchor_fixture_parser.py
- yoti_python_sdk/tests/test_anchor.py
- yoti_python_sdk/tests/test_client.py
* `anchor_parser.py`
* This is now where all parsing of anchor protobufs is done, separating the responsibility away from the `Anchor` object which is now just a model.
* This has also reduced the cognitive complexity of the anchor parsing
* Moved unknown anchor type into `yoti_python_sdk.config` as this is where source and verifier also lives
> SDK-1293: Refactor anchor parsing

- examples/yoti_example_django/yoti_example/views.py
- examples/yoti_example_flask/app.py
- yoti_python_sdk/profile.py
- yoti_python_sdk/tests/test_client.py
* `Profile` now stores all image attributes (PNG or JPEG currently) as an Image object rather than just the raw bytes
* Example projects have been updated to reflect this
> SDK-1296: Update Profile to store selfie as an Image object

- yoti_python_sdk/client.py
- yoti_python_sdk/dynamic_sharing_service/share_url.py
- yoti_python_sdk/endpoint.py
* The `endpoint` module was changed when the signed request builder was introduced to allow users to get endpoints without query parameters, using an optional boolean flag as a parameter to make it backwards compatible
* In the major, everything internally should be using the signed request builder, which no longer requires endpoints to have query parameters added
> SDK-1165: Refactor endpoint module

- yoti_python_sdk/document_details.py
* Defaulted non-required properties on `document_details` to `None` so we don't have to use hacky way of accessing a private property that might not have been initialised
> SDK-1286: Document Details private properties

- yoti_python_sdk/anchor_parser.py
- yoti_python_sdk/attribute.py
- yoti_python_sdk/attribute_parser.py
- yoti_python_sdk/multivalue.py
- yoti_python_sdk/tests/test_anchor.py
- yoti_python_sdk/tests/test_attribute.py
* In the previous major version, multivalue attribute values were introduced that were returned as a tuple rather than a list.
* In python, tuples are immutable if the objects inside are also immutable.  All of the models that we use hide the internal representation of attributes on an object, and use @property methods therefore making our models also immutable.
* All of the parsers (attribute and anchor) have been updated to return tuples instead of lists.  This still allows users to access data in exactly the same way as before, but ensures immutability of data returned from a share.
> SDK-916: Introduce immutability to all attributes and anchors

- yoti_python_sdk/tests/test_profile.py
* Added tests to the human `Profile` for attributes such as `date_of_birth` (this is now a date object rather than a string), `given_names` etc.
> SDK-1287: Profile tests

- yoti_python_sdk/activity_details.py
- yoti_python_sdk/attribute_parser.py
- yoti_python_sdk/date_parser.py
- yoti_python_sdk/document_details.py
- yoti_python_sdk/tests/test_date_parser.py
* `date_parser`
* I have added a load of helper functions which can be used to quickly parse dates/timestamps into the correct format, with all of the timezones set.
* By centralising where all dates are formatted, we can easily make changes if needed which should be reflected throughout the whole SDK (previously each module controlled it's own date parsing)
> SDK-1297: Refactor usage of date_parser

- examples/yoti_example_django/Dockerfile
- examples/yoti_example_django/docker-compose.yml
- examples/yoti_example_flask/Dockerfile
- examples/yoti_example_flask/docker-compose.yml
* Removes Yoti as a requirement from requirements.txt
* Modify the Dockerfiles for flask and Django so that the Yoti SDK is sent as part of
the build context. Because of the change in build context the dockerfile
has been moved to more readily indicate the directory that should be
sent. Readme instructions have been updated accordingly as well.
> SDK-1056: Use manual path twiddling to include Yoti SDK in sys.path

- .dependabot/config.yml
- examples/yoti_example_django/requirements.in
- examples/yoti_example_django/requirements.txt
- Closed the dependabot PR as it was the wrong base branch
- Have added dependabot config so that it uses development as the base branch, and also adds us as reviewers
> SDK-1322: Dependabot

- .pylintrc
- setup.py
* Updated pylint configuration to correctly ignore certain directories (such as auto-generated protobuf files), as well as to ignore specific pylint rules that may conflict with black formatter.
> SDK-1337: Update pylint configuration

- yoti_python_sdk/document_details.py
- yoti_python_sdk/tests/test_document_details.py
Support for parsing redacted aadhaar numbers
* Removed regex validation from `DocumentDetails`
> SDK-1443: Remove regex validation from document details

- requirements.in
- requirements.txt
Aside from being a security update, Cryptography 2.8 also has:
- support for Python 3.8
- support for OpenSSL 1.1.1d.
- And no longer depends on asn1crypto.
Release notes: https://cryptography.io/en/latest/changelog/
> SDK-1484: Update Cryptography: 2.7 -> 2.8

- .coveragerc
- sonar-project.properties
- yoti_python_sdk/doc_scan/session/retrieve/id_document_resource_response.py
- yoti_python_sdk/tests/doc_scan/session/retrieve/test_id_document_resource_response.py
- yoti_python_sdk/version.py
* `IdDocumentResourceResponse` now correctly inherits `ResourceResponse`
* Although none of the properties were missing, tasks on all ID documents were being parsed as generic `TaskResponse` objects.
* `TextExtractionTaskResponse` should now be available in the list of tasks
> Hotfix 2.11.1

- sonar-project.properties
- yoti_python_sdk/doc_scan/client.py
- yoti_python_sdk/tests/doc_scan/test_doc_scan_client.py
- yoti_python_sdk/version.py
* The incorrect default API URL was being used by the `DocScanClient`
> Hotfix 2.11.2

- requirements.in
- requirements.txt
- sonar-project.properties
- yoti_python_sdk/dynamic_sharing_service/extension/third_party_attribute_extension.py
- yoti_python_sdk/tests/dynamic_sharing_service/extension/test_third_party_attribute_extension.py
- yoti_python_sdk/version.py
- Update Attribute Issuance Expiry Date format to be milliseconds, not microseconds
Encountered a quirk with pytz timezones (from https://stackoverflow.com/questions/4008960/pytz-and-etc-gmt-5):
> In order to conform with the POSIX style, those zones beginning with "Etc/GMT" have their sign reversed from what most people expect. In this style, zones west of GMT have a positive sign and those east have a negative sign.
Have included this comment in the test, since I think it's quite valuable information when viewing the code!
> SDK-1589: Expiry date format

- requirements.in
- requirements.txt
- sonar-project.properties
- yoti_python_sdk/dynamic_sharing_service/extension/third_party_attribute_extension.py
- yoti_python_sdk/tests/dynamic_sharing_service/extension/test_third_party_attribute_extension.py
- yoti_python_sdk/version.py
- Update Attribute Issuance Expiry Date format to be milliseconds, not microseconds
> 2.12.1 release

- requirements.in
- requirements.txt
- setup.py
enum34 installation seems to clash with `enum` in path for _some_ environments (we found this for our integration tests using python-alpine docker images).
See:
- https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag
- https://github.com/iterative/dvc/issues/1995
Tried the other solutions mentioned there, removing asn1 is the cleanest, as it never installs enum34 in the first place
> Revert to asn1 2.2.0 to avoid using enum34

- .travis.yml
- README.md
- Use pytest instead of py.test (see https://stackoverflow.com/questions/39495429/py-test-vs-pytest-command)
> The py.test invocation is the old and busted joint. pytest is the new hotness (since 3.0). py.test and pytest invocations will coexist for a long time I guess, but at some point py.test might be deprecated. So I would recommend to #dropthedot.
> NA: use pytest instead of py.test

- yoti_python_sdk/doc_scan/session/create/check/document_authenticity.py
- yoti_python_sdk/doc_scan/session/create/check/face_match.py
- yoti_python_sdk/doc_scan/session/create/check/liveness.py
- yoti_python_sdk/doc_scan/session/create/check/requested_check.py
- yoti_python_sdk/doc_scan/session/create/filter/document_filter.py
- yoti_python_sdk/doc_scan/session/create/filter/document_restrictions_filter.py
- yoti_python_sdk/doc_scan/session/create/filter/orthogonal_restrictions_filter.py
- yoti_python_sdk/doc_scan/session/create/filter/required_id_document.py
- yoti_python_sdk/doc_scan/session/create/notification_config.py
- yoti_python_sdk/doc_scan/session/create/sdk_config.py
- yoti_python_sdk/doc_scan/session/create/session_spec.py
- yoti_python_sdk/doc_scan/session/create/task/requested_task.py
- yoti_python_sdk/doc_scan/session/create/task/text_extraction.py
- yoti_python_sdk/tests/doc_scan/session/create/filter/test_document_restriction_builder.py
- yoti_python_sdk/utils.py
Even if the objects don't have any values which currently serialize to null, I thought it would be best to specify that we don't want this behaviour, and then if we add any in the future, they will be excluded if null.
The alternative to this would be to ignore these values by default, and then we can override in any methods where we need to.
> SDK-1718: Remove null values from JSON payload

- yoti_python_sdk/doc_scan/exception/doc_scan_exception.py
- yoti_python_sdk/tests/doc_scan/exception/test_doc_scan_exception.py
- yoti_python_sdk/tests/mocks.py
- Formatted response error is now included in `DocScanException` message
> SDK-1582: Include response error in exception message

- examples/doc_scan/app.py
- yoti_python_sdk/doc_scan/session/create/check/document_authenticity.py
- yoti_python_sdk/tests/doc_scan/session/create/check/test_requested_document_authenticity_check.py
- Allow the configuration of the `manual_check` value for requested Document Authenticity checks
- `RequestedDocumentAuthenticityCheckBuilder.build()` is no longer static. Python 2 implementations must change this to `RequestedDocumentAuthenticityCheckBuilder().build()`
> SDK-1732: Allow manual check to be configured on authenticity checks

- examples/doc_scan/app.py
- yoti_python_sdk/doc_scan/client.py
- yoti_python_sdk/tests/doc_scan/mocks.py
- yoti_python_sdk/tests/doc_scan/test_doc_scan_client.py
- `DocScanClient.get_media_content()` will now return `None` for `204` no content responses
> SDK-1809: Support media responses with no content

- setup.py
- sonar-project.properties
- yoti_python_sdk/dynamic_sharing_service/extension/__init__.py
- yoti_python_sdk/dynamic_sharing_service/policy/dynamic_policy_builder.py
- yoti_python_sdk/tests/dynamic_sharing_service/policy/test_dynamic_policy_builder.py
- `DynamicPolicyBuilder().with_document_images()`
- `accept_self_asserted` option can now be passed to `DynamicPolicyBuilder` methods
- Added `pytz` requirement to _setup.py_
- `ThirdPartyAttributeExtension` can now be imported from `yoti_python_sdk.dynamic_sharing_service.extension`
> SDK-1615: Dynamic Scenario

- yoti_python_sdk/doc_scan/session/create/filter/orthogonal_restrictions_filter.py
- yoti_python_sdk/doc_scan/support/supported_documents.py
- yoti_python_sdk/dynamic_sharing_service/policy/source_constraint_builder.py
- yoti_python_sdk/tests/doc_scan/session/create/subcheck/test_issuing_authority_sub_check.py
- yoti_python_sdk/tests/doc_scan/support/test_supported_documents.py
- yoti_python_sdk/tests/dynamic_sharing_service/policy/test_source_constraint_builder.py
adding non-latin support for session and supported documents
> SDK-2027: adding non-latin support for session and supported documents

- setup.py
This is the source of a bug in which this package will break other systems by allowing the incompatible version 4.* of protobuf to be installed.
We are having to pin the version of protobuf ourselves in order to get around this issue.
Traceback:
`File "yoti-python-sdk-rightly\yoti_python_sdk\protobuf\attribute_public_api\ContentType_pb2.py", line 32, in <module>
_descriptor.EnumValueDescriptor(
File "lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
_message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade …
> (urgent) bugfix: mismatch in protobuf dep between requirements.txt and setup.py
